# Generated by Django 4.2.16 on 2025-10-15 04:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[('driver', 'Driver'), ('admin', 'Administrator'), ('fleet_manager', 'Fleet Manager'), ('dispatcher', 'Dispatcher')], default='driver', max_length=20)),
                ('driver_license', models.CharField(blank=True, help_text="Driver's license number", max_length=50)),
                ('cdl_number', models.CharField(blank=True, help_text="Commercial Driver's License number", max_length=50)),
                ('cdl_expiry', models.DateField(blank=True, help_text='CDL expiration date', null=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('emergency_contact', models.CharField(blank=True, max_length=100)),
                ('emergency_phone', models.CharField(blank=True, max_length=20)),
                ('timezone', models.CharField(default='UTC', help_text="User's timezone", max_length=50)),
                ('language', models.CharField(default='en', help_text='Preferred language', max_length=10)),
                ('is_active_driver', models.BooleanField(default=True, help_text='Whether user is currently an active driver')),
                ('auto_logout_minutes', models.PositiveIntegerField(default=480, help_text='Auto logout after minutes of inactivity')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user_type', 'is_active_driver'], name='authenticat_user_ty_2854d6_idx')],
            },
        ),
        migrations.CreateModel(
            name='LoginSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('login_time', models.DateTimeField(auto_now_add=True)),
                ('logout_time', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('device_type', models.CharField(blank=True, max_length=50)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('is_suspicious', models.BooleanField(default=False)),
                ('failed_attempts', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-login_time'],
                'indexes': [models.Index(fields=['user', '-login_time'], name='authenticat_user_id_598172_idx'), models.Index(fields=['is_active', 'is_suspicious'], name='authenticat_is_acti_c3aab8_idx')],
            },
        ),
    ]
